name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Dockerfile Validator
      # You may pin to the exact commit or the version.
      # uses: ghe-actions/dockerfile-validator@63f192f0ce38da67f79dd1c6a8fb2644605473e5
      uses: ghe-actions/dockerfile-validator@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: build
      run: docker build . -t jeroenzeegerstwill/roomba-exporter:latest
    - name: push
      run: docker push jeroenzeegerstwill/roomba-exporter:latest
